In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor

from xgboost import XGBRegressor

In [2]:
df = pd.read_csv("insurance_pre.csv")

In [3]:
df

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
df = pd.get_dummies(df, drop_first=True).astype(int)

In [5]:
df

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
X = df.drop("charges", axis=1)
y = df["charges"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
ada = AdaBoostRegressor()
ada.fit(X_train, y_train)

ada_pred = ada.predict(X_test)
ada_r2 = r2_score(y_test, ada_pred)

print("AdaBoost R2 Score:", ada_r2)

AdaBoost R2 Score: 0.7940356639632044

In [8]:
gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)

gb_pred = gb.predict(X_test)
gb_r2 = r2_score(y_test, gb_pred)

print("Gradient Boosting R2 Score:", gb_r2)

Gradient Boosting R2 Score: 0.839591958415931

In [ ]:

xgb = XGBRegressor()
xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_r2 = r2_score(y_test, xgb_pred)

print("XGBoost R2 Score:", xgb_r2)

In [ ]:
print("\nModel Comparison:")
print("AdaBoost:", ada_r2)
print("Gradient Boosting:", gb_r2)
print("XGBoost:", xgb_r2)

In [ ]:
!pip install xgboost